reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol apply-reuse.sh --year 2024 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/angular.json --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/angular.json --year 2023 --copyright "Jörn Bethune"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/cypress.config.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/cypress/e2e/app-initialization.cy.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/cypress/fixtures/example.json --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/cypress/support/commands.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/cypress/support/e2e.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/cypress/tsconfig.json --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/.eslintrc.json --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/.gitignore --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/package.json --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/package.json --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/package-lock.json --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/.prettierrc --year 2024 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/proxy.conf.json --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/README.md --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/README.md --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/scripts/bundle-assets.js --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/scripts/dear-mep.js --year 2024 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/app.component.html --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/app.component.scss --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/app.component.scss --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/app.component.spec.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/app.component.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/app.config.ts --year 2024 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/app.initializer.ts --year 2024 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/calling/calling.component.html --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/calling/calling.component.scss --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/calling/calling.component.spec.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/calling/calling.component.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/calling/steps/feedback-step/feedback-step.component.html --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/calling/steps/feedback-step/feedback-step.component.scss --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/calling/steps/feedback-step/feedback-step.component.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/calling/steps/home-step/home-step.component.html --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/calling/steps/home-step/home-step.component.scss --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/calling/steps/home-step/home-step.component.spec.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/calling/steps/home-step/home-step.component.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/calling/steps/setup-step/setup-step.component.html --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/calling/steps/setup-step/setup-step.component.scss --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/calling/steps/setup-step/setup-step.component.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/calling/steps/update-call-schedule/update-call-schedule.component.html --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/calling/steps/update-call-schedule/update-call-schedule.component.scss --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/calling/steps/update-call-schedule/update-call-schedule.component.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/calling/steps/update-call-schedule/update-call-schedule.spec.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/calling/steps/verify-number-step/verification-step.enum.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/calling/steps/verify-number-step/verify-number.component.html --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/calling/steps/verify-number-step/verify-number.component.scss --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/calling/steps/verify-number-step/verify-number.component.scss --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/calling/steps/verify-number-step/verify-number.component.spec.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/calling/steps/verify-number-step/verify-number.component.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/common/directives/responsive.directive.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/common/interceptors/auth.interceptor.spec.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/common/interceptors/auth.interceptor.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/common/interceptors/base-url.interceptor.spec.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/common/interceptors/base-url.interceptor.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/common/interceptors/retry.interceptor.spec.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/common/interceptors/retry.interceptor.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/common/interceptors/timeout.interceptor.spec.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/common/interceptors/timeout.interceptor.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/common/material/shadow-root-overlay-container.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/common/pipes/safe.pipe.spec.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/common/pipes/safe.pipe.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/common/pipes/to-absolute.pipe.spec.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/common/pipes/to-absolute.pipe.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/common/services/base-url.service.spec.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/common/services/base-url.service.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/common/util/delay.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/common/util/markup.util.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/common/util/nameof.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/common/util/object.util.spec.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/common/util/object.util.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/common/util/phone-number.util.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/common/util/string.util.spec.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/common/util/string.util.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/common/util/time.util.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/common/util/typed-http-error.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/common/util/url.util.spec.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/common/util/url.util.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/calling-buttons/calling-buttons.component.html --year 2024 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/calling-buttons/calling-buttons.component.scss --year 2024 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/calling-buttons/calling-buttons.component.ts --year 2024 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/country-select/country-select.component.html --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/country-select/country-select.component.scss --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/country-select/country-select.component.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/error-modal/error-dialog.model.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/error-modal/error-modal.component.html --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/error-modal/error-modal.component.scss --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/error-modal/error-modal.component.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/footer/footer.component.html --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/footer/footer.component.spec.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/footer/footer.component.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/language-switch/language-switch.component.html --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/language-switch/language-switch.component.scss --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/language-switch/language-switch.component.spec.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/language-switch/language-switch.component.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/mep-detail/mep-detail.component.html --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/mep-detail/mep-detail.component.scss --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/mep-detail/mep-detail.component.spec.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/mep-detail/mep-detail.component.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/phone-number-input/phone-number-input.component.css --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/phone-number-input/phone-number-input.component.html --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/phone-number-input/phone-number-input.component.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/phone-number-input/phone-number-validation-errors.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/select-mep/select-mep.component.html --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/select-mep/select-mep.component.scss --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/select-mep/select-mep.component.spec.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/select-mep/select-mep.component.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/social-icon/social-icon.component.html --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/social-icon/social-icon.component.scss --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/social-icon/social-icon.component.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/talking-points/talking-points.component.html --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/talking-points/talking-points.component.scss --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/talking-points/talking-points.component.scss --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/talking-points/talking-points.component.spec.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/talking-points/talking-points.component.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/title/title.component.html --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/title/title.component.scss --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/title/title.component.spec.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/components/title/title.component.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/model/calling-step.enum.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/model/day-of-week.enum.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/model/phone-number.model.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/model/time-of-day.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/services/authentication/authentication.service.spec.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/services/authentication/authentication.service.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/services/calling/calling.service.spec.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/services/calling/calling.service.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/services/config/app-config.model.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/services/config/config.service.spec.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/services/config/config.service.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/services/error/error.service.spec.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/services/error/error.service.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/services/feedback/feedback.service.spec.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/services/feedback/feedback.service.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/services/l10n/l10n.service.spec.ts --year 2024 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/services/l10n/l10n.service.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/services/local-storage/local-storage.service.spec.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/services/local-storage/local-storage.service.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/services/office-hours/office-hours.service.spec.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/services/office-hours/office-hours.service.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/services/routing/routing-state-manager.service.spec.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/services/routing/routing-state-manager.service.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/services/select-destination/select-destination.service.spec.ts --year 2024 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/services/select-destination/select-destination.service.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/services/time/time.service.spec.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/services/time/time.service.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/testing/fixtures.module.ts --year 2024 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/testing/testing-config.ts --year 2024 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/testing/transloco-testing.module.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/testing/util/next-tick.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/app/transloco.providers.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/environments/environment.development.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/environments/environment.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/favicon.ico --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/index.html --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/main.ts --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/style/dear-mep-inner.scss --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/style/dear-mep.scss --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/style/themes/default-dark.scss --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/src/style/themes/variables.scss --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/test-page/index.html --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/transloco.config.js --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/tsconfig.app.json --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/tsconfig.json --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol client/tsconfig.spec.json --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol doc/data-conversion.md --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol doc/data-conversion.md --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol doc/data-protection.md --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol doc/glossary.md --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol doc/glossary.md --year 2023 --copyright "Thomas Lohninger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol doc/img/dear-mep-talk-thumb.png --year 2024 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol doc/ivr/compile_messages.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol doc/ivr/.gitignore --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol doc/ivr.md --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol doc/ivr/messages.csv --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol doc/metrics.md --year 2024 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol doc/scheduler.md --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol doc/security.md --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol doc/selecting-destinations.md --year 2024 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol doc/theming.md --year 2024 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol .editorconfig --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol .editorconfig --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol .github/workflows/build.yaml --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol .github/workflows/build.yaml --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol .gitignore --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol README.md --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol README.md --year 2024 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/alembic.ini --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/build-db.sh --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/build-db.sh --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/api/authtoken.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/api/authtoken.py --year 2023 --copyright "Jörn Bethune"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/api/v1.py --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/api/v1.py --year 2023 --copyright "Jörn Bethune"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/api/v1.py --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/api/v1.py --year 2023 --copyright "Philipp Aaron Becker"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/cli/check.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/cli/convert.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/cli/db.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/cli/db.py --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/cli/dump.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/cli/importing.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/cli/__init__.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/cli/__main__.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/cli/serve.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/cli/version.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/config.py --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/config.py --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/config.py --year 2023 --copyright "Jörn Bethune"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/config.py --year 2023 --copyright "Philipp Aaron Becker"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/convert/audio.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/convert/blobfile.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/convert/dump.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/convert/europarl/media.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/convert/europarl/rollcallvote.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/convert/ffmpeg.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/convert/image.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/convert/__init__.py --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/convert/lz.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/convert/parltrack/mep.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/convert/tabular.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/convert/xml.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/database/connection.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/database/connection.py --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/database/importing.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/database/__init__.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/database/__init__.py --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/database/lint.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/database/models.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/database/models.py --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/database/models.py --year 2023 --copyright "Jörn Bethune"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/database/models.py --year 2023 --copyright "Philipp Aaron Becker"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/database/query.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/database/query.py --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/database/query.py --year 2023 --copyright "Jörn Bethune"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/database/query.py --year 2023 --copyright "Philipp Aaron Becker"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/example-config.yaml --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/example-config.yaml --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/example-config.yaml --year 2023 --copyright "axfr2200"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/example-config.yaml --year 2023 --copyright "Jörn Bethune"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/example-config.yaml --year 2023 --copyright "Thomas Lohninger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/example-config.yaml --year 2023 --copyright "Hugo Peixoto"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/example-config.yaml --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/example-config.yaml --year 2023 --copyright "aura"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/example-config.yaml --year 2023 --copyright "Philipp Aaron Becker"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/http_client.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/__init__.py --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/l10n.py --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/logging.yaml --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/main.py --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/main.py --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/main.py --year 2023 --copyright "Jörn Bethune"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/markdown_files.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/models.py --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/models.py --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/models.py --year 2023 --copyright "Jörn Bethune"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/phone/abstract.py --year 2023 --copyright "Jörn Bethune"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/phone/abstract.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/phone/abstract.py --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/phone/developer_phone.py --year 2023 --copyright "Jörn Bethune"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/phone/developer_phone.py --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/phone/developer_phone.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/phone/elks/elks.py --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/phone/elks/elks.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/phone/elks/__init__.py --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/phone/elks/metrics.py --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/phone/elks/metrics.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/phone/elks/models.py --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/phone/elks/ongoing_calls.py --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/phone/elks_phone.py --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/phone/elks_phone.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/phone/elks/utils.py --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/phone/ivr.py --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/progress.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/ratelimit.py --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/ratelimit.py --year 2023 --copyright "Jörn Bethune"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/schedules/calls.py --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/schedules/__init__.py --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/schedules/__init__.py --year 2024 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/static_files/demo.html --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/static_files/demo.html --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/dearmep/static_files/__init__.py --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/example-markdown/docs/privacy/de.md --year 2023 --copyright "axfr2200"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/example-markdown/docs/privacy/de.md --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/example-markdown/docs/privacy/de.md --year 2023 --copyright "muminpappa"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/example-markdown/docs/privacy/de.md --year 2023 --copyright "Thomas Lohninger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/example-markdown/docs/privacy/de.md --year 2023 --copyright "Tobias Mühlberger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/example-markdown/docs/privacy/en.md --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/example-markdown/docs/privacy/en.md --year 2023 --copyright "Hugo Peixoto"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/example-markdown/docs/privacy/en.md --year 2023 --copyright "Thomas Lohninger"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/example-markdown/docs/privacy/fr.md --year 2023 --copyright "aura"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/example-markdown/docs/privacy/pt.md --year 2023 --copyright "Hugo Peixoto"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/example-markdown/docs/privacy/sv.md --year 2023 --copyright "axfr2200"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/example-markdown/static/styles.css --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/example-markdown/templates/default.html.jinja --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/.gitignore --year 2023 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/migrations/env.py --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/migrations/script.py.mako --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/migrations/versions/20231121-8d7e440490bf_inital_alembic_database_state.py --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/migrations/versions/20231214-5d2aefe5f0ad_add_scheduler_relevant_tables.py --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/poetry.lock --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/poetry.lock --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/poetry.lock --year 2023 --copyright "Jörn Bethune"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/pyproject.toml --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/pyproject.toml --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/pyproject.toml --year 2023 --copyright "Jörn Bethune"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/README.md --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/README.md --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/tests/api/test_api_l10n.py --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/tests/conftest.py --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/tests/conftest.py --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/tests/geo_ip/create_test_db.py --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/tests/geo_ip/README.md --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/tests/geo_ip/test.mmdb --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/test.sh --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/tests/test_config.py --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/tests/test_config.py --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/tests/test_l10n.py --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/tests/test_metrics.py --year 2022 --copyright "Tim Weber"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/tests/test_ongoing_calls.py --year 2023 --copyright "iameru"
reuse annotate --fallback-dot-license --license AGPL-3.0-or-later --copyright-prefix spdx-symbol server/tests/test_phonenumbers.py --year 2023 --copyright "Tim Weber"
