"""add scheduled_calls and queued_calls tables

Revision ID: fba7d048d5c7
Revises: 8d7e440490bf
Create Date: 2023-12-06 14:35:26.354237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fba7d048d5c7'
down_revision: Union[str, None] = '8d7e440490bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queued_calls',
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('postponed_to', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('phone_number')
    )
    op.create_table('scheduled_calls',
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('last_queued_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('phone_number', 'day')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_calls')
    op.drop_table('queued_calls')
    # ### end Alembic commands ###
