"""add scheduled_calls and scheduled_calls_queue table

Revision ID: 62bdc70736c6
Revises: 8d7e440490bf
Create Date: 2023-12-01 14:12:00.047469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '62bdc70736c6'
down_revision: Union[str, None] = '8d7e440490bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queued_calls',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('postponed_to', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('scheduled_calls',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('last_queued_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'day')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_calls')
    op.drop_table('queued_calls')
    # ### end Alembic commands ###
